# App
spring.application.name=ictpm41

# Database
spring.datasource.url=jdbc:postgresql://127.0.0.1:5433/ictpm41
spring.datasource.username=ictpm41_user
spring.datasource.password=ictpm41_pass
spring.datasource.driver-class-name=org.postgresql.Driver



# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


# JWT
jwt.secret=ictpm41-secret-key-change-in-production-minimum-256-bits
jwt.expiration=86400000

# AI Service
ai.service.url=http://localhost:8000

# Open-Meteo
openmeteo.base.url=https://api.open-meteo.com/v1

# Scheduler - runs every 6 hours
scheduler.weather.fetch.cron=0 0 */6 * * *

# Server
server.port=8080